### PR TITLE
Build small binary without debug symbols by default

### PR DESCRIPTION
**Pull request by timvaillancourt**
This adds the -w and -s compiler flags to 'go build' to cause debugging symbols to be stripped. This creates much smaller binaries.

Before (6.9MB):
```
$ ls -alh mgo-statsd
-rwxrwxr-x. 1 tim tim 6.9M Apr 30 14:19 mgo-statsd
```

With the "-w and -s" change (4.9MB, 32% smaller):
```
$ ls -alh mgo-statsd
-rwxrwxr-x. 1 tim tim 4.7M Apr 30 14:19 mgo-statsd
```

Users who would like debugging symbols can comment-out Line 17 (the 'GO_LDFLAGS' line) in build.sh. This is also mentioned in the build.sh comment.

### CODE REVIEW

**Comment by scullxbones** [comment]
I think this is good - one request:

Can you add a flag to `build.sh` that re-introduces the debug flags, rather than requiring users to comment out the line?

**Comment by timvaillancourt** [comment]
Good idea @scullxbones, I'll add a flag for enabling debug

**Comment by timvaillancourt** [comment]
@scullxbones I have added flags to support this with bash getopt:

Help:
```
$ ./build.sh -h
Usage ./build.sh [flags]
	-h  Print Help
	-d  Enable debugging symbols in binary
```

To enable the debug symbols you need to run:
```
./build.sh -d
```

**Comment by scullxbones** [comment]
Yep LGTM, thanks!

**Pull request merged**
